### ISSUE TITLE
ImportCourseWithoutUpload is missing referenceRequest option is sdk

### ISSUE THREAD

**Issue by parth3724** [RusticiSoftware/scormcloud-api-v2-client-java#14]
As per the api documentation - https://rustici-docs.s3.amazonaws.com/engine/21.1.x/api/apiV2.html#/course/ImportCourseWithoutUpload,

importRequest can be set using 
"referenceRequest": {
    "url": "string",
    "webPathToCourse": "string",
    "mediaFileMetadata": {
      "title": "string",
      "description": "string",
      "contentLanguage": "string",
      "moveOn": "string",
      "estimatedDuration": 0,
      "activityType": "string",
      "xAPIActivityId": "string",
      "cmi5PublisherId": "string"
    }
  },

but, this option is missing from sdk.
SDK supports fetchRequest, mediaFileReferenceRequest and connectorReferenceRequest only.

Is it possible to add referenceRequest to the sdk ?

**Comment by mjschuetze102** [comment]
The linked documentation is for a different product (Rustici Engine) that we offer. The APIs are purposefully very similar, but there are differences between them. SCORM Cloud's documentation can be found here: https://cloud.scorm.com/docs/v2/reference/swagger/

I would recommend contacting us at `support@rusticisoftware.com` and we can set you on the right path for working with whichever product you are trying to connect with

**Comment by mjschuetze102** [comment]
I'm going to go ahead and close this ticket. Let me know if you have any other questions.
